apiVersion: v1
kind: Namespace
metadata:
  name: ns-accept
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accept-redis-deployment
  namespace: ns-accept
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      automountServiceAccountToken: true
      hostIPC: true
      hostPID: true
      hostNetwork: true
      serviceAccountName: default
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
      containers:
        - name: accept-redis-container
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
                - NET_RAW
            runAsNonRoot: false
            runAsGroup: 0
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            privileged: true
          image: redis:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
              hostPort: 6379
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-accept
  namespace: ns-accept
  labels:
    app: e2e-accept
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: violation-acceptance-role-binding
  namespace: ns-accept
subjects:
- kind: ServiceAccount
  name: sa-accept
  namespace: ns-accept
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
